apiVersion: v1
kind: Service
metadata:
  name: mysql-service 
  namespace: my-project
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    nodePort: 31003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: my-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: ubuntu 
          - name: MYSQL_DATABASE
            value: springblog
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            value: ubuntu        
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim