apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app # Deployment name
  namespace: my-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec: 
      containers:
      - name: frontend
        image: fatma24/frontend:latest
        imagePullPolicy: "Always"
        env:
        - name: BACKEND_URL
          value: "http://192.168.74.140:32000"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
  namespace: my-project
spec:
  type: NodePort
  selector:
    app: angular-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31004
